import base64
from django.core.files import File

from django.urls import reverse
from rest_framework import status
from rest_framework.test import APITestCase, APIClient
from django.core.files.uploadedfile import SimpleUploadedFile
from user.models import User
from .models import Post


class PostTests(APITestCase):

    def setUp(self):
        self.access_token = None
        self.posts_id = None

        user = User.objects.create_superuser(
            last_name="Lastname",
            first_name="Firstname",
            email="exemple@exemple.com",
            username="exemple@exemple.com",
            password='password1234',
            is_superuser=True
        )

        regular_user = User.objects.create_user(
            last_name="Lastname",
            first_name="Firstname",
            email="regular@exemple.com",
            username="regular@exemple.com",
            password='password1234',
        )

    def test_create_posts_valid_value(self):

        url = '/token'
        data = {'username': 'exemple@exemple.com', 'password': 'password1234'}
        response = self.client.post(url, data, format='json')
        data = response.json()

        self.client.credentials(HTTP_AUTHORIZATION='Bearer ' + data['access'])

        image_file = open('./posts/data/data.png', 'rb')
        data = {
            "title": "Title",
            "image": image_file,
            "content": "Post content",
        }

        url = '/posts/'
        response = self.client.post(url, data, format='multipart')
        self.assertEqual(response.status_code, status.HTTP_201_CREATED)

    def test_create_posts_unlogin_user(self):

        image_file = open('./posts/data/data.png', 'rb')
        data = {
            "title": "Title",
            "image": image_file,
            "content": "Post content",
        }

        url = '/posts/'
        response = self.client.post(url, data, format='multipart')
        self.assertEqual(response.status_code, status.HTTP_401_UNAUTHORIZED)

    def test_create_posts_missing_value(self):

        url = '/token'
        data = {'username': 'exemple@exemple.com', 'password': 'password1234'}
        response = self.client.post(url, data, format='json')
        data = response.json()

        self.client.credentials(HTTP_AUTHORIZATION='Bearer ' + data['access'])

        data = {

            "title": "",
            "image": "",
            "content": "",
        }

        url = '/posts/'
        response = self.client.post(url, data, format='multipart')
        data = response.json()

        self.assertTrue(True, data['errors']['title'])
        self.assertTrue(True, data['errors']['image'])
        self.assertTrue(True, data['errors']['content'])

        self.assertEqual(response.status_code, status.HTTP_404_NOT_FOUND)

    def test_create_posts_invalid_value(self):

        url = '/token'
        data = {'username': 'exemple@exemple.com', 'password': 'password1234'}
        response = self.client.post(url, data, format='json')
        data = response.json()

        self.client.credentials(HTTP_AUTHORIZATION='Bearer ' + data['access'])

        data = {
            'title': 'skdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdj',
            'image': 'skdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdj',
            'content': 'skdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdj',
        }

        url = '/posts/'
        response = self.client.post(url, data, format='multipart')
        data = response.json()

        self.assertTrue(True, data['errors']['title'])
        self.assertTrue(True, data['errors']['image'])
        self.assertTrue(True, data['errors']['content'])

        self.assertEqual(response.status_code, status.HTTP_404_NOT_FOUND)

    def test_update_posts_valid_value(self):

        url = '/token'
        data = {'username': 'exemple@exemple.com', 'password': 'password1234'}
        response = self.client.post(url, data, format='json')
        data = response.json()

        self.client.credentials(HTTP_AUTHORIZATION='Bearer ' + data['access'])

        # Create posts
        image_file = open('./posts/data/data.png', 'rb')
        data = {
            "title": "Title",
            "image": image_file,
            "content": "Post content",
        }

        url = '/posts/'
        response = self.client.post(url, data, format='multipart')

        # Read all posts and get create posts id
        url = '/posts/all'
        response = self.client.get(url, format='json')
        data = response.json()
        self.posts_id = data[0]["public_id"]

        # Update posts
        image_file = open('./posts/data/data.png', 'rb')
        data = {
            "title": "New Title",
            "image": image_file,
            "content": "New post content",
        }

        url = '/posts/' + self.posts_id
        response = self.client.put(url, data, format='multipart')
        self.assertEqual(response.status_code, status.HTTP_200_OK)

    def test_update_posts_missing_value(self):

        url = '/token'
        data = {'username': 'exemple@exemple.com', 'password': 'password1234'}
        response = self.client.post(url, data, format='json')
        data = response.json()

        self.client.credentials(HTTP_AUTHORIZATION='Bearer ' + data['access'])

        # Create posts
        image_file = open('./posts/data/data.png', 'rb')
        data = {
            "title": "Title",
            "image": image_file,
            "content": "Post content",
        }

        url = '/posts/'
        response = self.client.post(url, data, format='multipart')

        # Read all posts and get create posts id
        url = '/posts/all'
        response = self.client.get(url, format='json')
        data = response.json()
        self.posts_id = data[0]["public_id"]

        # Update posts
        data = {
            "title": "",
            "image": "",
            "content": "",
        }

        url = '/posts/' + self.posts_id
        response = self.client.put(url, data, format='json')
        data = response.json()

        self.assertTrue(True, data['errors']['title'])
        self.assertTrue(True, data['errors']['image'])
        self.assertTrue(True, data['errors']['content'])

        self.assertEqual(response.status_code, status.HTTP_404_NOT_FOUND)

    def test_update_posts_invalid_value(self):

        url = '/token'
        data = {'username': 'exemple@exemple.com', 'password': 'password1234'}
        response = self.client.post(url, data, format='json')
        data = response.json()

        self.client.credentials(HTTP_AUTHORIZATION='Bearer ' + data['access'])

        # Create posts
        image_file = open('./posts/data/data.png', 'rb')
        data = {
            "title": "Title",
            "image": image_file,
            "content": "Post content",
        }

        url = '/posts/'
        response = self.client.post(url, data, format='multipart')

        # Read all posts and get create posts id
        url = '/posts/all'
        response = self.client.get(url, format='json')
        data = response.json()
        self.posts_id = data[0]["public_id"]

        data = {
            'title': 'skdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdj',
            'image': 'skdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdj',
            'content': 'skdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdj',
        }

        url = '/posts/' + self.posts_id
        response = self.client.put(url, data, format='json')
        data = response.json()

        self.assertTrue(True, data['errors']['title'])
        self.assertTrue(True, data['errors']['image'])
        self.assertTrue(True, data['errors']['content'])

        self.assertEqual(response.status_code, status.HTTP_404_NOT_FOUND)

    def test_update_posts_unauthorize_user(self):

        url = '/token'
        data = {'username': 'exemple@exemple.com', 'password': 'password1234'}
        response = self.client.post(url, data, format='json')
        data = response.json()

        self.client.credentials(HTTP_AUTHORIZATION='Bearer ' + data['access'])

        # Create posts
        image_file = open('./posts/data/data.png', 'rb')
        data = {
            "title": "Title",
            "image": image_file,
            "content": "Post content",
        }

        url = '/posts/'
        response = self.client.post(url, data, format='multipart')

        # Read all posts and get create posts id
        url = '/posts/all'
        response = self.client.get(url, format='json')
        data = response.json()
        self.posts_id = data[0]["public_id"]

        url = '/token'
        data = {'username': 'regular@exemple.com', 'password': 'password1234'}
        response = self.client.post(url, data, format='json')
        data = response.json()

        self.client.credentials(HTTP_AUTHORIZATION='Bearer ' + data['access'])

        # Update posts
        image_file = open('./posts/data/data.png', 'rb')
        data = {
            "title": "Title",
            "image": image_file,
            "content": "Post content",
        }

        url = '/posts/' + self.posts_id
        response = self.client.put(url, data, format='multipart')
        self.assertEqual(response.status_code, status.HTTP_403_FORBIDDEN)

    def test_read_posts_valid_value(self):

        url = '/token'
        data = {'username': 'exemple@exemple.com', 'password': 'password1234'}
        response = self.client.post(url, data, format='json')
        data = response.json()

        self.client.credentials(HTTP_AUTHORIZATION='Bearer ' + data['access'])

        # Create posts
        image_file = open('./posts/data/data.png', 'rb')
        data = {
            "title": "Title",
            "image": image_file,
            "content": "Post content",
        }

        url = '/posts/'
        response = self.client.post(url, data, format='multipart')

        # Read all posts and get create posts id
        url = '/posts/all'
        response = self.client.get(url, format='json')
        data = response.json()
        self.posts_id = data[0]["public_id"]

        self.client.credentials(HTTP_AUTHORIZATION='')

        url = '/posts/' + self.posts_id
        response = self.client.get(url, format='json')
        self.assertEqual(response.status_code, status.HTTP_200_OK)

    def test_read_all_posts_valid_value(self):

        url = '/token'
        data = {'username': 'exemple@exemple.com', 'password': 'password1234'}
        response = self.client.post(url, data, format='json')
        data = response.json()

        self.client.credentials(HTTP_AUTHORIZATION='Bearer ' + data['access'])

        image_file = open('./posts/data/data.png', 'rb')
        data = {
            "title": "Title",
            "image": image_file,
            "content": "Post content",
        }

        url = '/posts/'
        response = self.client.post(url, data, format='multipart')

        # Read all posts and get create posts id
        url = '/posts/all'
        response = self.client.get(url, format='json')
        data = response.json()
        self.assertEqual(response.status_code, status.HTTP_200_OK)

    def test_delete_posts_valid_value(self):

        url = '/token'
        data = {'username': 'exemple@exemple.com', 'password': 'password1234'}
        response = self.client.post(url, data, format='json')
        data = response.json()

        self.client.credentials(HTTP_AUTHORIZATION='Bearer ' + data['access'])

        # Create posts
        image_file = open('./posts/data/data.png', 'rb')
        data = {
            "title": "Title",
            "image": image_file,
            "content": "Post content",
        }

        url = '/posts/'
        response = self.client.post(url, data, format='multipart')

        # Read all posts and get create posts id
        url = '/posts/all'
        response = self.client.get(url, format='json')
        data = response.json()
        self.posts_id = data[0]["public_id"]

        url = '/posts/' + self.posts_id
        response = self.client.delete(url, format='json')
        self.assertEqual(response.status_code, status.HTTP_200_OK)

    def test_delete_posts_unauthorize_user(self):

        url = '/token'
        data = {'username': 'exemple@exemple.com', 'password': 'password1234'}
        response = self.client.post(url, data, format='json')
        data = response.json()

        self.client.credentials(HTTP_AUTHORIZATION='Bearer ' + data['access'])

        # Create posts
        image_file = open('./posts/data/data.png', 'rb')
        data = {
            "title": "Title",
            "image": image_file,
            "content": "Post content",
        }

        url = '/posts/'
        response = self.client.post(url, data, format='multipart')

        # Read all posts and get create posts id
        url = '/posts/all'
        response = self.client.get(url, format='json')
        data = response.json()
        self.posts_id = data[0]["public_id"]

        url = '/token'
        data = {'username': 'regular@exemple.com', 'password': 'password1234'}
        response = self.client.post(url, data, format='json')
        data = response.json()

        self.client.credentials(HTTP_AUTHORIZATION='Bearer ' + data['access'])

        url = '/posts/' + self.posts_id
        response = self.client.delete(url, format='json')
        self.assertEqual(response.status_code, status.HTTP_403_FORBIDDEN)

    def test_like_posts_valid_value(self):

        url = '/token'
        data = {'username': 'exemple@exemple.com', 'password': 'password1234'}
        response = self.client.post(url, data, format='json')
        data = response.json()

        self.client.credentials(HTTP_AUTHORIZATION='Bearer ' + data['access'])

        # Create posts
        image_file = open('./posts/data/data.png', 'rb')
        data = {
            "title": "Title",
            "image": image_file,
            "content": "Post content",
        }

        url = '/posts/'
        response = self.client.post(url, data, format='multipart')

        # Read all posts and get create posts id
        url = '/posts/all'
        response = self.client.get(url, format='json')
        data = response.json()
        self.posts_id = data[0]["public_id"]

        url = '/posts/like/' + self.posts_id
        response = self.client.post(url, format='json')
        self.assertEqual(response.status_code, status.HTTP_200_OK)

    def test_like_unlogin_user(self):

        url = '/token'
        data = {'username': 'exemple@exemple.com', 'password': 'password1234'}
        response = self.client.post(url, data, format='json')
        data = response.json()

        self.client.credentials(HTTP_AUTHORIZATION='Bearer ' + data['access'])

        # Create posts
        image_file = open('./posts/data/data.png', 'rb')
        data = {
            "title": "Title",
            "image": image_file,
            "content": "Post content",
        }

        url = '/posts/'
        response = self.client.post(url, data, format='multipart')

        # Read all posts and get create posts id
        url = '/posts/all'
        response = self.client.get(url, format='json')
        data = response.json()
        self.posts_id = data[0]["public_id"]

        self.client.credentials(HTTP_AUTHORIZATION='Bearer ')

        url = '/posts/like/' + self.posts_id
        response = self.client.post(url, format='json')
        self.assertEqual(response.status_code, status.HTTP_401_UNAUTHORIZED)

    def test_remove_like_posts_valid_value(self):

        url = '/token'
        data = {'username': 'exemple@exemple.com', 'password': 'password1234'}
        response = self.client.post(url, data, format='json')
        data = response.json()

        self.client.credentials(HTTP_AUTHORIZATION='Bearer ' + data['access'])

        # Create posts
        image_file = open('./posts/data/data.png', 'rb')
        data = {
            "title": "Title",
            "image": image_file,
            "content": "Post content",
        }

        url = '/posts/'
        response = self.client.post(url, data, format='multipart')

        # Read all posts and get create posts id
        url = '/posts/all'
        response = self.client.get(url, format='json')
        data = response.json()
        self.posts_id = data[0]["public_id"]

        url = '/posts/like/' + self.posts_id
        response = self.client.post(url, format='json')

        url = '/posts/like/' + self.posts_id
        response = self.client.post(url, format='json')

        url = '/posts/' + self.posts_id
        response = self.client.get(url, format='json')
        data = response.json()
        is_liked = data['user_like']

        self.assertEqual(is_liked, False)

    def test_remove_unlike_with_like_posts_valid_value(self):

        url = '/token'
        data = {'username': 'exemple@exemple.com', 'password': 'password1234'}
        response = self.client.post(url, data, format='json')
        data = response.json()

        self.client.credentials(HTTP_AUTHORIZATION='Bearer ' + data['access'])

        # Create posts
        image_file = open('./posts/data/data.png', 'rb')
        data = {
            "title": "Title",
            "image": image_file,
            "content": "Post content",
        }

        url = '/posts/'
        response = self.client.post(url, data, format='multipart')

        # Read all posts and get create posts id
        url = '/posts/all'
        response = self.client.get(url, format='json')
        data = response.json()
        self.posts_id = data[0]["public_id"]

        url = '/posts/unlike/' + self.posts_id
        response = self.client.post(url, format='json')

        url = '/posts/like/' + self.posts_id
        response = self.client.post(url, format='json')

        url = '/posts/' + self.posts_id
        response = self.client.get(url, format='json')
        data = response.json()
        is_liked = data['user_like']
        is_unliked = data['user_unlike']

        self.assertEqual(is_liked, True)
        self.assertEqual(is_unliked, False)

    def test_unlike_posts_valid_value(self):

        url = '/token'
        data = {'username': 'exemple@exemple.com', 'password': 'password1234'}
        response = self.client.post(url, data, format='json')
        data = response.json()

        self.client.credentials(HTTP_AUTHORIZATION='Bearer ' + data['access'])

        # Create posts
        image_file = open('./posts/data/data.png', 'rb')
        data = {
            "title": "Title",
            "image": image_file,
            "content": "Post content",
        }

        url = '/posts/'
        response = self.client.post(url, data, format='multipart')

        # Read all posts and get create posts id
        url = '/posts/all'
        response = self.client.get(url, format='json')
        data = response.json()
        self.posts_id = data[0]["public_id"]

        url = '/posts/unlike/' + self.posts_id
        response = self.client.post(url, format='json')
        self.assertEqual(response.status_code, status.HTTP_200_OK)

    def test_unlike_unlogin_user(self):

        url = '/token'
        data = {'username': 'exemple@exemple.com', 'password': 'password1234'}
        response = self.client.post(url, data, format='json')
        data = response.json()

        self.client.credentials(HTTP_AUTHORIZATION='Bearer ' + data['access'])

        # Create posts
        image_file = open('./posts/data/data.png', 'rb')
        data = {
            "title": "Title",
            "image": image_file,
            "content": "Post content",
        }

        url = '/posts/'
        response = self.client.post(url, data, format='multipart')

        # Read all posts and get create posts id
        url = '/posts/all'
        response = self.client.get(url, format='json')
        data = response.json()
        self.posts_id = data[0]["public_id"]

        self.client.credentials(HTTP_AUTHORIZATION='Bearer ')

        url = '/posts/unlike/' + self.posts_id
        response = self.client.post(url, format='json')
        self.assertEqual(response.status_code, status.HTTP_401_UNAUTHORIZED)

    def test_remove_unlike_posts_valid_value(self):

        url = '/token'
        data = {'username': 'exemple@exemple.com', 'password': 'password1234'}
        response = self.client.post(url, data, format='json')
        data = response.json()

        self.client.credentials(HTTP_AUTHORIZATION='Bearer ' + data['access'])

        # Create posts
        image_file = open('./posts/data/data.png', 'rb')
        data = {
            "title": "Title",
            "image": image_file,
            "content": "Post content",
        }

        url = '/posts/'
        response = self.client.post(url, data, format='multipart')

        # Read all posts and get create posts id
        url = '/posts/all'
        response = self.client.get(url, format='json')
        data = response.json()
        self.posts_id = data[0]["public_id"]

        url = '/posts/unlike/' + self.posts_id
        response = self.client.post(url, format='json')

        url = '/posts/unlike/' + self.posts_id
        response = self.client.post(url, format='json')

        url = '/posts/' + self.posts_id
        response = self.client.get(url, format='json')
        data = response.json()
        is_unliked = data['user_unlike']

        self.assertEqual(is_unliked, False)

    def test_remove_like_with_unlike_posts_valid_value(self):

        url = '/token'
        data = {'username': 'exemple@exemple.com', 'password': 'password1234'}
        response = self.client.post(url, data, format='json')
        data = response.json()

        self.client.credentials(HTTP_AUTHORIZATION='Bearer ' + data['access'])

        # Create posts
        image_file = open('./posts/data/data.png', 'rb')
        data = {
            "title": "Title",
            "image": image_file,
            "content": "Post content",
        }

        url = '/posts/'
        response = self.client.post(url, data, format='multipart')

        # Read all posts and get create posts id
        url = '/posts/all'
        response = self.client.get(url, format='json')
        data = response.json()
        self.posts_id = data[0]["public_id"]

        url = '/posts/like/' + self.posts_id
        response = self.client.post(url, format='json')

        url = '/posts/unlike/' + self.posts_id
        response = self.client.post(url, format='json')

        url = '/posts/' + self.posts_id
        response = self.client.get(url, format='json')
        data = response.json()
        is_liked = data['user_like']
        is_unliked = data['user_unlike']

        self.assertEqual(is_liked, False)
        self.assertEqual(is_unliked, True)
