from django.urls import reverse
from rest_framework import status
from rest_framework.test import APITestCase, APIClient
from user.models import User
from .models import Post


class PostTests(APITestCase):

    def setUp(self):
        self.client = APIClient()
        self.access_token = None
        self.posts_id = None

        user = User.objects.create_superuser(
            last_name="Lastname",
            first_name="Firstname",
            email="exemple@exemple.com",
            username="exemple@exemple.com",
            password='password1234',
            token='foo',
            is_superuser=True
        )

        regular_user = User.objects.create_user(
            last_name="Lastname",
            first_name="Firstname",
            email="regular@exemple.com",
            username="regular@exemple.com",
            password='password1234',
            token='foo',
        )

    def test_create_posts_valid_value(self):

        url = '/token'
        data = {'username': 'exemple@exemple.com', 'password': 'password1234'}
        response = self.client.post(url, data, format='json')
        data = response.json()
        
        self.client.credentials(HTTP_AUTHORIZATION='Bearer ' + data['access'])
        
        data = {
            "title": "Title",
            "image_url": "image url",
            "content": "Post content",
        }

        url = '/posts/'
        response = self.client.post(url, data, format='json')
        self.assertEqual(response.status_code, status.HTTP_201_CREATED)
    
    def test_create_posts_unlogin_user(self):

        data = {
            "title": "Title",
            "image_url": "image url",
            "content": "Post content",
        }

        url = '/posts/'
        response = self.client.post(url, data, format='json')
        self.assertEqual(response.status_code, status.HTTP_401_UNAUTHORIZED)
          
    def test_create_posts_missing_value(self):

        url = '/token'
        data = {'username': 'exemple@exemple.com', 'password': 'password1234'}
        response = self.client.post(url, data, format='json')
        data = response.json()
        
        self.client.credentials(HTTP_AUTHORIZATION='Bearer ' + data['access'])
        

        data = {
            
            "title": "",
            "image_url": "",
            "content": "",
        }
        
        url = '/posts/'
        response = self.client.post(url, data, format='json')
        data = response.json()
        
        self.assertTrue(True, data['errors']['title'])
        self.assertTrue(True, data['errors']['image_url'])
        self.assertTrue(True, data['errors']['content'])
        
        self.assertEqual(response.status_code, status.HTTP_404_NOT_FOUND)
    
    def test_create_posts_invalid_value(self):

        url = '/token'
        data = {'username': 'exemple@exemple.com', 'password': 'password1234'}
        response = self.client.post(url, data, format='json')
        data = response.json()
        
        self.client.credentials(HTTP_AUTHORIZATION='Bearer ' + data['access'])
        
        data = {
            'title': 'skdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdj',
            'image_url': 'skdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdj',
            'content': 'skdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdj',
        }
        
        url = '/posts/'
        response = self.client.post(url, data, format='json')
        data = response.json()
        
        self.assertTrue(True, data['errors']['title'])
        self.assertTrue(True, data['errors']['image_url'])
        self.assertTrue(True, data['errors']['content'])
        
        self.assertEqual(response.status_code, status.HTTP_404_NOT_FOUND)   
             
    def test_update_posts_valid_value(self):
        
        url = '/token'
        data = {'username': 'exemple@exemple.com', 'password': 'password1234'}
        response = self.client.post(url, data, format='json')
        data = response.json()
        
        self.client.credentials(HTTP_AUTHORIZATION='Bearer ' + data['access'])
        
        # Create posts
        data = {
            "title": "Title",
            "image_url": "image url",
            "content": "Post content",
        }

        
        url = '/posts/'
        response = self.client.post(url, data, format='json')
        
        # Read all posts and get create posts id
        url = '/posts/all'
        response = self.client.get(url, format='json')
        data = response.json()
        self.posts_id = data[0]["public_id"]
        
        
        # Update posts
        data = {
            "title": "New Title",
            "image_url": "image url",
            "content": "New post content",
        }

        
        url = '/posts/' + self.posts_id
        response = self.client.put(url, data, format='json')
        self.assertEqual(response.status_code, status.HTTP_200_OK)

    def test_update_posts_missing_value(self):
        
        url = '/token'
        data = {'username': 'exemple@exemple.com', 'password': 'password1234'}
        response = self.client.post(url, data, format='json')
        data = response.json()
        
        self.client.credentials(HTTP_AUTHORIZATION='Bearer ' + data['access'])
        
        # Create posts
        data = {
            "title": "Title",
            "image_url": "image url",
            "content": "Post content",
        }

        
        url = '/posts/'
        response = self.client.post(url, data, format='json')
        
        # Read all posts and get create posts id
        url = '/posts/all'
        response = self.client.get(url, format='json')
        data = response.json()
        self.posts_id = data[0]["public_id"]
        
        
        # Update posts
        data = {
            "title": "",
            "image_url": "",
            "content": "",
        }

        
        url = '/posts/' + self.posts_id
        response = self.client.put(url, data, format='json')
        data = response.json()
        
        self.assertTrue(True, data['errors']['title'])
        self.assertTrue(True, data['errors']['image_url'])
        self.assertTrue(True, data['errors']['content'])
        
        self.assertEqual(response.status_code, status.HTTP_404_NOT_FOUND)  
        
    def test_update_posts_invalid_value(self):
        
        url = '/token'
        data = {'username': 'exemple@exemple.com', 'password': 'password1234'}
        response = self.client.post(url, data, format='json')
        data = response.json()
        
        self.client.credentials(HTTP_AUTHORIZATION='Bearer ' + data['access'])
        
        # Update posts
        data = {
            "title": "Title",
            "image_url": "image url",
            "content": "Post content",
        }

                
        url = '/posts/'
        response = self.client.post(url, data, format='json')
        
        # Read all posts and get create posts id
        url = '/posts/all'
        response = self.client.get(url, format='json')
        data = response.json()
        self.posts_id = data[0]["public_id"]
        
        data = {
            'title': 'skdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdj',
            'image_url': 'skdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdj',
            'content': 'skdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdjskdjskjdksjksjskjdsksjdj',
        }
        
        url = '/posts/' + self.posts_id
        response = self.client.put(url, data, format='json')
        data = response.json()
        
        self.assertTrue(True, data['errors']['title'])
        self.assertTrue(True, data['errors']['image_url'])
        self.assertTrue(True, data['errors']['content'])
        
        self.assertEqual(response.status_code, status.HTTP_404_NOT_FOUND)  
        

    def test_update_posts_unauthorize_user(self):
        
        url = '/token'
        data = {'username': 'exemple@exemple.com', 'password': 'password1234'}
        response = self.client.post(url, data, format='json')
        data = response.json()
        
        self.client.credentials(HTTP_AUTHORIZATION='Bearer ' + data['access'])
        
        # Create posts
        data = {
            "title": "Title",
            "image_url": "image url",
            "content": "Post content",
        }

        
        url = '/posts/'
        response = self.client.post(url, data, format='json')
        
        # Read all posts and get create posts id
        url = '/posts/all'
        response = self.client.get(url, format='json')
        data = response.json()
        self.posts_id = data[0]["public_id"]
        
        url = '/token'
        data = {'username': 'regular@exemple.com', 'password': 'password1234'}
        response = self.client.post(url, data, format='json')
        data = response.json()
        
        self.client.credentials(HTTP_AUTHORIZATION='Bearer ' + data['access'])
        
        # Update posts
        data = {
            "title": "Title",
            "image_url": "image url",
            "content": "Post content",
        }

        
        url = '/posts/' + self.posts_id
        response = self.client.put(url, data, format='json')
        self.assertEqual(response.status_code, status.HTTP_403_FORBIDDEN)
        
    def test_read_posts_valid_value(self):
        
        url = '/token'
        data = {'username': 'exemple@exemple.com', 'password': 'password1234'}
        response = self.client.post(url, data, format='json')
        data = response.json()
        
        self.client.credentials(HTTP_AUTHORIZATION='Bearer ' + data['access'])
        
        # Create posts
        data = {
            "title": "Title",
            "image_url": "image url",
            "content": "Post content",
        }

        
        url = '/posts/'
        response = self.client.post(url, data, format='json')
        
        # Read all posts and get create posts id
        url = '/posts/all'
        response = self.client.get(url, format='json')
        data = response.json()
        self.posts_id = data[0]["public_id"]
        
        self.client.credentials(HTTP_AUTHORIZATION='')
        
        url = '/posts/' + self.posts_id
        response = self.client.get(url, format='json')
        self.assertEqual(response.status_code, status.HTTP_200_OK)

    def test_read_all_posts_valid_value(self):
        
        url = '/token'
        data = {'username': 'exemple@exemple.com', 'password': 'password1234'}
        response = self.client.post(url, data, format='json')
        data = response.json()
        
        self.client.credentials(HTTP_AUTHORIZATION='Bearer ' + data['access'])
        
        data = {
            "title": "Title",
            "image_url": "image url",
            "content": "Post content",
        }

        
        url = '/posts/'
        response = self.client.post(url, data, format='json')
        
        # Read all posts and get create posts id
        url = '/posts/all'
        response = self.client.get(url, format='json')
        data = response.json()
        self.assertEqual(response.status_code, status.HTTP_200_OK)
        
        
    def test_delete_posts_valid_value(self):
        
        url = '/token'
        data = {'username': 'exemple@exemple.com', 'password': 'password1234'}
        response = self.client.post(url, data, format='json')
        data = response.json()
        
        self.client.credentials(HTTP_AUTHORIZATION='Bearer ' + data['access'])
        
        # Create posts
        data = {
            "title": "Title",
            "image_url": "image url",
            "content": "Post content",
        }

        
        url = '/posts/'
        response = self.client.post(url, data, format='json')
        
        # Read all posts and get create posts id
        url = '/posts/all'
        response = self.client.get(url, format='json')
        data = response.json()
        self.posts_id = data[0]["public_id"]
        
        url = '/posts/' + self.posts_id
        response = self.client.delete(url, format='json')
        self.assertEqual(response.status_code, status.HTTP_200_OK)
    
    def test_delete_posts_unauthorize_user(self):
        
        url = '/token'
        data = {'username': 'exemple@exemple.com', 'password': 'password1234'}
        response = self.client.post(url, data, format='json')
        data = response.json()
        
        self.client.credentials(HTTP_AUTHORIZATION='Bearer ' + data['access'])
        
        # Create posts
        data = {
            "title": "Title",
            "image_url": "image url",
            "content": "Post content",
        }

        
        url = '/posts/'
        response = self.client.post(url, data, format='json')
        
        # Read all posts and get create posts id
        url = '/posts/all'
        response = self.client.get(url, format='json')
        data = response.json()
        self.posts_id = data[0]["public_id"]
        
        url = '/token'
        data = {'username': 'regular@exemple.com', 'password': 'password1234'}
        response = self.client.post(url, data, format='json')
        data = response.json()
        
        self.client.credentials(HTTP_AUTHORIZATION='Bearer ' + data['access'])
        
        url = '/posts/' + self.posts_id
        response = self.client.delete(url, format='json')
        self.assertEqual(response.status_code, status.HTTP_403_FORBIDDEN)